### ISSUE TITLE
Prims algorithm is broken for large dimensional datasets

### ISSUE THREAD

**Issue by lmcinnes** [lmcinnes/hdbscan#32]
Run the Prims version of HDBSCAN on the digits dataset from sklearn and you will get awful results. Both Boruvka and the generic approach get it right. What's the problem here? Still to be determined.

**Comment by lmcinnes** [comment]
Resolved! The issue was not dimension, but rather than the numpy arrays were not contiguous in memory which interfered with cython internals in hdbscan which were using pointer arithmetic inside array buffers for efficiency. The solution was 1) mark in the cython that we need contiguous arrays! (this should later be done elsewhere too!) 2) check for contiguous arrays and duplicate to a contiguous array if it isn't before handing it off to the cython code.

**Comment by djaym7** [comment]
2021 - still getting this error 
Cannot generate Minimum Spanning Tree; the implemented Prim's does not produce the full minimum spanning tree

**Comment by lmcinnes** [comment]
Is this from the current master (I think some changes to Prim's were merged recently) or the current pip release (which doesn't have those recent changes)?

**Comment by djaym7** [comment]
> Is this from the current master (I think some changes to Prim's were merged recently) or the current pip release (which doesn't have those recent changes)?

It's from current Master

**Comment by lmcinnes** [comment]
Try the current master, as it may resolve some of those issues.

**Comment by djaym7** [comment]
5425cd2a3c7a13a9f5ed82a25e896fff4a6e521c commit still gives the same error
![image](https://user-images.githubusercontent.com/12378820/146255344-a8bd5042-3a40-4c20-99cd-f27a9d8856b0.png)

**Comment by djaym7** [comment]
Any update on this ?

**Comment by lmcinnes** [comment]
I think you need to force not using Prim's. That may be painful.
